import { CATEGORY, RISK_STATUS } from "@/mock";
import { Risk } from "@/types";

const risks: Risk[] = [
  {
    id: "1",
    dateRaised: new Date(Date.now()),
    riskName: 'Insider-Threat',
    impact: 3,
    likelihood: 2,
    owner: 'MMR',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam, nesciunt.',
    consequences: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam, nesciunt.',
    category: "",
    subcategory: "",
    riskStatus: RISK_STATUS[Math.floor(Math.random() * RISK_STATUS.length)].id,
    affectedAsset: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam, nesciunt.',
    updatedDate: new Date(Date.now()),
  },
  {
    id: "2",
    dateRaised: new Date(Date.now()),
    riskName: 'DDOS',
    impact: 1,
    likelihood: 4,
    owner: 'STC',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam, nesciunt.',
    consequences: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam, nesciunt.',
    category: "",
    subcategory: "",
    riskStatus: RISK_STATUS[Math.floor(Math.random() * RISK_STATUS.length)].id,
    affectedAsset: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam, nesciunt.',
    updatedDate: new Date(Date.now()),
  },
  {
    id: "3",
    dateRaised: new Date(Date.now()),
    riskName: 'Reputational',
    impact: 5,
    likelihood: 3,
    owner: 'Uber',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam, nesciunt.',
    consequences: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam, nesciunt.',
    category: "",
    subcategory: "",
    riskStatus: RISK_STATUS[Math.floor(Math.random() * RISK_STATUS.length)].id,
    affectedAsset: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam, nesciunt.',
    updatedDate: new Date(Date.now()),
  },
  {
    id: "4",
    dateRaised: new Date(Date.now()),
    riskName: 'Phishing',
    impact: 2,
    likelihood: 2,
    owner: 'Modern Life co.',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam, nesciunt.',
    consequences: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam, nesciunt.',
    category: "",
    subcategory: "",
    riskStatus: RISK_STATUS[Math.floor(Math.random() * RISK_STATUS.length)].id,
    affectedAsset: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam, nesciunt.',
    updatedDate: new Date(Date.now()),
  },
  {
    id: "5",
    dateRaised: new Date(Date.now()),
    riskName: 'Environmental Fire Protection',
    impact: 1,
    likelihood: 5,
    owner: 'Health co.',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam, nesciunt.',
    consequences: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam, nesciunt.',
    category: "",
    subcategory: "",
    riskStatus: RISK_STATUS[Math.floor(Math.random() * RISK_STATUS.length)].id,
    affectedAsset: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam, nesciunt.',
    updatedDate: new Date(Date.now()),
  },
  {
    id: "6",
    dateRaised: new Date(Date.now()),
    riskName: 'Cloud Vendor Compromised',
    impact: 5,
    likelihood: 5,
    owner: 'Azure',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam, nesciunt.',
    consequences: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam, nesciunt.',
    category: "",
    subcategory: "",
    riskStatus: RISK_STATUS[Math.floor(Math.random() * RISK_STATUS.length)].id,
    affectedAsset: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam, nesciunt.',
    updatedDate: new Date(Date.now()),
  },
  {
    id: "7",
    dateRaised: new Date(Date.now()),
    riskName: 'Material delivery is delayed',
    impact: 4,
    likelihood: 1,
    owner: 'GRC',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam, nesciunt.',
    consequences: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam, nesciunt.',
    category: "",
    subcategory: "",
    riskStatus: RISK_STATUS[Math.floor(Math.random() * RISK_STATUS.length)].id,
    affectedAsset: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam, nesciunt.',
    updatedDate: new Date(Date.now()),
  },
  {
    id: "8",
    dateRaised: new Date(Date.now()),
    riskName: 'Machinery breakdowns',
    impact: 4,
    likelihood: 1,
    owner: 'STC',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam, nesciunt.',
    consequences: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam, nesciunt.',
    category: "",
    subcategory: "",
    riskStatus: RISK_STATUS[Math.floor(Math.random() * RISK_STATUS.length)].id,
    affectedAsset: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam, nesciunt.',
    updatedDate: new Date(Date.now()),
  },
];

export const RISKS: Risk[] = risks.map((r) => {
  const category = CATEGORY[Math.floor(Math.random() * CATEGORY.length)]
  const subcategory = category.subCategory?.[Math.floor(Math.random() *category.subCategory?.length)].id ?? ""
  return { ...r, category: category.id, subcategory }
})